services:
  postgres:
    image: postgres:15
    container_name: weather_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: weather_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: always

  kestra:
    build:
      context: ..
      dockerfile: docker/Dockerfile.kestra
    container_name: weather_kestra
    user: "root"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: server local
    environment:
      KESTRA_CONFIGURATION: |
        micronaut:
          io:
            watch:
              enabled: true
              paths:
                - /app/flows
        kestra:
          server:
            basic-auth:
              username: admin@kestra.io
              password: Admin1234
          tutorialFlows:
            enabled: false
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
    volumes:
      - kestra_data:/app/storage
      - ../orchestration/kestra/flows:/app/flows
      - ../ingestion:/app/ingestion
      - ../data:/app/data
      - /tmp/kestra-wd:/tmp/kestra-wd
    restart: always

volumes:
  postgres_data:
  kestra_data: